--1.1)
CREATE SEQUENCE buyno_seq START WITH 2001;

--1.2)
CREATE TABLE TBL_POSTCODE (
	POSTCODE char(6) NOT NULL,
	AREA1 VARCHAR2(200) NOT NULL 
);

--1.3)
ALTER TABLE "TBL_CUSTOM#" 
ADD (POSTCODE char(6));

--1.4)
ALTER TABLE "TBL_CUSTOM#"
MODIFY (CONSTRAINT fk_postcode FOREIGN KEY (POSTCODE)
REFERENCES TBL_POSTCODE(POSTCODE));

--2.1)
SELECT * FROM "TBL_BUY#" tb WHERE BUY_DATE >= '2022-02-11';
--2.2)
SELECT PCODE,PNAME,PRICE FROM "TBL_PRODUCT#" tp 
WHERE price = (SELECT max(price) FROM "TBL_PRODUCT#"); 
--2.3) 
SELECT CATEGORY, MAX(PRICE) FROM "TBL_PRODUCT#" tp 
GROUP BY CATEGORY ;
--2.4)
 SELECT tc.CUSTOM_ID , tc.NAME, tb.QUANTITY 
 FROM "TBL_CUSTOM#" tc ,"TBL_BUY#" tb 
 WHERE tc.CUSTOM_ID = tb.CUSTOM_ID 
 AND pcode = 'IPAD011';
--2.5)
 SELECT tc.CUSTOM_ID , tc.NAME, tc.age 
 FROM "TBL_CUSTOM#" tc
 LEFT OUTER JOIN "TBL_BUY#" tb 
 ON tc.CUSTOM_ID = tb.CUSTOM_ID
 WHERE pcode = NULL;
--2.6)
SELECT BUY_DATE AS "BUY_DATE2", tp."MAX(MONEY)"
FROM "TBL_BUY#" tb,
(SELECT SUM(PRICE) AS "MAX(MONEY)" FROM "TBL_PRODUCT#" tp2 
GROUP BY PCODE) tp 
WHERE tb.PCODE = tp.PCODE ;


--3.1)
INSERT INTO TBL_POSTCODE(POSTCODE, AREA1)
VALUES ('137964', '서울특별시 서초구 서초2동');
INSERT INTO TBL_POSTCODE(POSTCODE, AREA1)
VALUES ('138761', '서울특별시 송파구 장지동 409880');
INSERT INTO TBL_POSTCODE(POSTCODE, AREA1)
VALUES ('412510', '경기도 고양시 덕양구 벽제동');
INSERT INTO TBL_POSTCODE(POSTCODE, AREA1)
VALUES ('409880', '인천광역시 옹진군 자월면');

--3.2)

--3.3)
CREATE VIEW v_custom_info
AS 
SELECT tc.CUSTOM_ID , tp.POSTCODE , tp.AREA1
FROM "TBL_CUSTOM#" tc , TBL_POSTCODE tp 
WHERE tc.POSTCODE = tp.POSTCODE ;



SELECT * FROM v_custom_info ;




